add check_secrets job to verify the secret_detection artifact

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,16 +1,42 @@
-# You can override the included template(s) by including variable overrides
-# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
-# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
-# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
-# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
-# Note that environment variables can be set in several places
-# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
 stages:
-- test
-- secret-detection
+- build
+- test-validate
+- plan
+
 variables:
   SECRET_DETECTION_ENABLED: 'true'
-secret_detection:
-  stage: secret-detection
+
 include:
 - template: Security/Secret-Detection.gitlab-ci.yml
+
+secret_detection:
+  stage: test-validate
+  tags:
+    - playground-bravo
+
+check_secrets:
+  stage: test-validate
+  tags:
+    - playground-bravo
+  needs:
+    - job: secret_detection
+      artifacts: true
+  script:
+    - |
+      if [ ! -f "gl-secret-detection-report.json" ]; then
+        echo "Secret detection report not found!"
+        exit 1
+      fi
+
+      if [ "$(jq '.vulnerabilities | length' gl-secret-detection-report.json)" -gt 0 ]; then
+        echo "Secrets detected in the codebase!"
+        jq -r '.vulnerabilities[] | "- \(.message) in \(.location.file):\(.location.start_line)"' \
+          gl-secret-detection-report.json
+        exit 1
+      else
+        echo "No secrets detected"
+      fi
+  rules:
+    - if: $CI_COMMIT_BRANCH == "master"
+    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
+
