Optimize CI: parallelize test and SAST check

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -69,6 +69,7 @@ deploy:
   - playground-bravo
   needs:
   - job: test
+  - job: check_sast
   before_script:
   - apk add --no-cache git openssh-client
   - eval $(ssh-agent -s)
@@ -82,10 +83,37 @@ deploy:
   rules:
   - if: $CI_COMMIT_BRANCH == "master"
 
-sast:
+semgrep-sast:
+  stage: static-test
+  tags:
+  - playground-bravo
+
+check_sast:
   stage: test
+  image: apteno/alpine-jq:latest
   tags:
   - playground-bravo
   needs:
+  - job: semgrep-sast
+    artifacts: true
   - job: check_secrets
   - job: lint
+  script:
+  - |
+    if [ ! -f "gl-sast-report.json" ]; then
+      echo "SAST report not found!"
+      exit 1
+    fi
+
+    VULN_COUNT=$(jq '.vulnerabilities | length' gl-sast-report.json)
+    if [ "$VULN_COUNT" -gt 0 ]; then
+      echo "SAST vulnerabilities detected!"
+      jq -r '.vulnerabilities[] | "- [\(.severity)] \(.name) in \(.location.file):\(.location.start_line)"' \
+        gl-sast-report.json
+      exit 1
+    else
+      echo "No SAST vulnerabilities detected"
+    fi
+  rules:
+  - if: $CI_COMMIT_BRANCH == "master"
+  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
